version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: finance_pg
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-finance}
      POSTGRES_USER: ${POSTGRES_USER:-finance}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-finance}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-finance} -d ${POSTGRES_DB:-finance}",
        ]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer:
    image: adminer:4
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  pgdata:
