# Generated by Django 4.2.23 on 2025-08-26 17:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='investors.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='investors.portfolio')),
            ],
            options={
                'indexes': [models.Index(fields=['portfolio', 'asset'], name='idx_position_portfolio_asset'), models.Index(fields=['asset'], name='idx_position_asset')],
            },
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('portfolio', 'asset'), name='uniq_position_portfolio_asset'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='chk_position_quantity_nonneg'),
        ),
    ]
