# Generated by Django 4.2.23 on 2025-08-29 16:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_position_position_uniq_position_portfolio_asset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioStat',
            fields=[
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stat', serialize=False, to='investors.portfolio')),
                ('port_vol', models.FloatField(blank=True, null=True)),
                ('sharpe_proxy', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
